name: Patching Suggestion
description: Suggest a new feature for patching a game.
title: "[PATCHING SUGGESTION]: "
labels: ["patch suggestion"]
projects: ["PurnPum/IPSHub"]
assignees:
  - PurnPum
body:
  - type: textarea
    id: suggestion-body
    attributes:
      label: Suggestion Details
      description: Please provide a clear and concise description of your suggestion or idea.
      placeholder: Please provide a clear and concise description of your suggestion or idea.
      value: ""
    validations:
      required: true
  - type: dropdown
    id: base_game
    attributes:
      label: Base Game
	  multiple: false
      description: Select, from the list below, the game this patching suggestion is intended to work with
      options:
        - "Pokémon: Yellow Edition"
        - "Pokémon: Crystal Edition"
      default: 0
    validations:
      required: true
  - type: dropdown
    id: implementer
    attributes:
      label: If this suggestion gets approved, do you plan on implementing it, or do you want to leave it on our features queue for us to develop it at some point?
      multiple: false
      options:
        - I will develop it myself
        - The team should develop it
