# Generated by Django 5.0.4 on 2024-06-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patchoption',
            name='github_issue',
        ),
        migrations.AddField(
            model_name='patch',
            name='patch_options',
            field=models.ManyToManyField(related_name='patches', to='patches.patchoption'),
        ),
        migrations.AlterField(
            model_name='patchoption',
            name='code_file',
            field=models.CharField(max_length=200),
        ),
    ]
