# Generated by Django 5.0.4 on 2024-06-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0002_remove_patchoption_github_issue_patch_patch_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='field_data',
            field=models.JSONField(default={'fields': {'activated': True}}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patchoption',
            name='fields',
            field=models.JSONField(default={'fields': {'activated': 'Boolean'}}),
            preserve_default=False,
        ),
    ]
