# Generated by Django 5.0.4 on 2024-08-02 19:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0003_patch_field_data_patchoption_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patch',
            name='field_data',
        ),
        migrations.RemoveField(
            model_name='patchoption',
            name='fields',
        ),
        migrations.AlterField(
            model_name='patchoption',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='POField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('field_type', models.CharField(max_length=100)),
                ('initial_data', models.JSONField()),
                ('parent_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfields', to='patches.pofield')),
                ('patch_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patches.patchoption')),
            ],
        ),
        migrations.CreateModel(
            name='PatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patches.patch')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patches.pofield')),
            ],
        ),
        migrations.AddConstraint(
            model_name='patchdata',
            constraint=models.UniqueConstraint(fields=('patch', 'field'), name='patchdata_identifier'),
        ),
    ]
