# Generated by Django 5.0.4 on 2024-08-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0004_remove_patch_field_data_remove_patchoption_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pofield',
            name='default_value',
            field=models.JSONField(null=True),
        ),
    ]
