# Generated by Django 5.0.4 on 2024-08-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0005_pofield_default_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patchoption',
            name='code_file',
        ),
        migrations.AddField(
            model_name='pofield',
            name='code_file',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
