# Generated by Django 5.0.4 on 2024-08-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0006_remove_patchoption_code_file_pofield_code_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pofield',
            name='default_value',
        ),
        migrations.AddField(
            model_name='pofield',
            name='default_data',
            field=models.JSONField(blank=True, default={'data': []}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pofield',
            name='initial_data',
            field=models.JSONField(blank=True),
        ),
    ]
