# Generated by Django 5.0.4 on 2024-08-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0007_remove_pofield_default_value_pofield_default_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patchdata',
            name='data',
            field=models.JSONField(),
        ),
    ]
