# Generated by Django 5.0.4 on 2024-08-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0008_alter_patchdata_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='download_link',
            field=models.URLField(default='xd', max_length=500),
            preserve_default=False,
        ),
    ]
