# Generated by Django 5.0.4 on 2024-08-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0009_patch_download_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='download_link',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='patch',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
