# Generated by Django 5.0.4 on 2024-08-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0010_alter_patch_download_link_alter_patch_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='patch_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, unique=True),
        ),
    ]
