# Generated by Django 5.0.4 on 2024-08-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0011_patch_patch_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patch',
            name='patch_hash',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
