# Generated by Django 5.0.4 on 2024-08-07 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0012_alter_patch_patch_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patchdata',
            name='data',
            field=models.CharField(max_length=10000),
        ),
    ]
