# Generated by Django 5.0.4 on 2024-08-10 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0014_difffile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pofield',
            name='code_file',
        ),
        migrations.AddField(
            model_name='difffile',
            name='trigger_value',
            field=models.CharField(default='True', max_length=10000),
            preserve_default=False,
        ),
    ]
