# Generated by Django 5.0.4 on 2024-08-16 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0015_remove_pofield_code_file_difffile_trigger_value'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatchFav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patches.patch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='patchfav',
            constraint=models.UniqueConstraint(fields=('patch', 'user'), name='patchfav_identifier'),
        ),
    ]
