# Generated by Django 5.0.4 on 2024-09-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patches', '0018_patchcommentlike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patch',
            name='normalized_name',
            field=models.CharField(default='temp', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patch',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
