# Generated by Django 5.0.4 on 2024-06-01 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image_ref', models.URLField()),
                ('name', models.CharField(max_length=50)),
                ('base_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='games.game')),
                ('parent_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='categories.category')),
            ],
        ),
    ]
