# Generated by Django 5.0.4 on 2024-09-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='normalized_name',
            field=models.CharField(default='temp', max_length=200),
            preserve_default=False,
        ),
    ]
