# Generated by Django 5.0.4 on 2025-10-28 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_category_normalized_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_ref',
        ),
    ]
