# Generated by Django 5.0.4 on 2024-06-01 17:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image_ref', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('developer', models.CharField(max_length=100)),
                ('best_emulator', models.CharField(max_length=200)),
                ('extra_info', models.URLField()),
            ],
        ),
    ]
