# Generated by Django 5.0.4 on 2024-06-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='best_emulator',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='image_ref',
            field=models.CharField(max_length=200),
        ),
    ]
