# Generated by Django 5.0.4 on 2024-06-02 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_best_emulator_alter_game_image_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='image_mini_ref',
            field=models.CharField(default='/static/images/pokemon_yellow_mini.png', max_length=200),
            preserve_default=False,
        ),
    ]
