# Generated by Django 5.0.4 on 2024-07-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_alter_game_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='best_emulator_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='best_emulator',
            field=models.CharField(max_length=100),
        ),
    ]
