# Generated by Django 5.0.4 on 2024-07-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_best_emulator_url_alter_game_best_emulator'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='type',
            field=models.CharField(default='xd', max_length=100),
            preserve_default=False,
        ),
    ]
