# Generated by Django 5.0.4 on 2024-08-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='repository',
            field=models.URLField(default='https://github.com'),
            preserve_default=False,
        ),
    ]
