import os
from pathlib import Path
import re
import sys
import base64
import requests

def post_comment(comment_url, comment_data):
  response = requests.post(comment_url, headers=headers, json=comment_data)

  if response.status_code == 201:
    print(f"Comment posted successfully.")
  else:
    print(f"Failed to post comment. Response: {response.content}")
    sys.exit(1)

def parse_issue_form_data():
  body = os.environ['ISSUE_BODY']
  title = os.environ['ISSUE_TITLE']

  # Extract data from the issue body
  body_pattern = r"(### Suggestion Details.*)(### Base Game\n\n)(.*)(\n\n)(### Implementer\n\n)(.*)"
  title_pattern = r"^(.*)(:[\s*])(.*)"

  base_game = re.search(body_pattern,body,re.DOTALL).group(3)
  implementer = re.search(body_pattern,body,re.DOTALL).group(6)
  description = re.search(title_pattern,title).group(3)
  
  return {'base_game': base_game, 'implementer': implementer, 'description': description}

def create_issue(base_game, description):
  new_branch = create_branch(ISSUE_NUMBER)
  title = f"[PATCH DEVELOPMENT]: {base_game}: {description}"

  md_file_path = Path(os.environ["CHECKOUT_DIRECTORY"]) / "patch_development.md"
  with open(md_file_path, 'r') as file:
    md_content = file.read()
    body = (
      f"**Original Suggestion:** #{ISSUE_NUMBER}\n\n"
      f"**Created branch:** [{new_branch}](https://github.com/{REPOSITORY}/tree/{new_branch})\n\n"
      f"---\n\n"
      f"{md_content}"  # Append the content of the .md file
    )
  base_game_label = BASE_GAME_LABELS[base_game]
  try:
    response = requests.post(
      GITHUB_API_ISSUES,
      headers=headers,
      json={
        'title': title,
        'body': body,
        'labels': ['patching/development', f"base_game/{base_game_label}", 'patching/user-developed'],
        'assignees': [ISSUE_AUTHOR],
      }
    )

    new_issue = response.json()
    return new_issue['number']
  except:
    print(f"Failed to create issue. Response: {response.content}")
    sys.exit(1)

def create_draft_pr(base_game,description):
  base_game_label = BASE_GAME_LABELS[base_game]
  new_branch = create_branch(ISSUE_NUMBER, is_draft_pr=True)
  try:
    response = requests.post(
      GITHUB_API_PULLS,
      headers=headers,
      json={
        'issue': int(ISSUE_NUMBER),
        'draft': True,
        'assignees': [ISSUE_AUTHOR],
        'base': 'patch_implementations',
        'head': new_branch,
      }
    )
    new_pr = response.json()
    new_pr_number = new_pr['number']
    
    response = requests.patch(
      f"{GITHUB_API_ISSUES}/{new_pr_number}",
      headers=headers,
      json={
        'title': f"[PATCH DEVELOPMENT]: {base_game}: {description}",
        'labels': ['patching/development','patching/pull-request', f"base_game/{base_game_label}", 'patching/team-developed'],
      }
    )
    return new_pr['number']
  except:
    print(f"Failed to create PR. Response: {response.content}")
    sys.exit(1)

def close_issue():
  data = {
    "state": "closed"
  }
    
  response = requests.patch(GITHUB_API_ISSUENUM, headers=headers, json=data)
    
  if response.status_code == 200:
    print(f"Issue #{ISSUE_NUMBER} closed successfully.")
  else:
    print(f"Failed to close the issue #{ISSUE_NUMBER}. Response: {response.content}")
    sys.exit(1)
  return response

def create_branch(issue_id, is_draft_pr=False):
  branchName = f"patchdev/{int(issue_id):04d}"
  
  response = requests.get(GITHUB_API_BRANCH, headers=headers)

  if response.status_code == 200:
    latest_commit_sha = response.json()["object"]["sha"]
    print(f"Latest commit SHA for {BASE_BRANCH}: {latest_commit_sha}")
  else:
    print(f"Failed to get base branch: {response.content}")
    sys.exit(1)

  data = {
    "ref": f"refs/heads/{branchName}",
    "sha": latest_commit_sha
  }
  response = requests.post(GITHUB_API_REFS, headers=headers, json=data)

  if response.status_code == 201:
    print(f"Branch '{branchName}' created successfully.")
  else:
    print(f"Failed to create branch: {response.content}")
    sys.exit(1)
  
  if is_draft_pr:
    file_path = "static/diffs/diffs/deleteme.txt"
    file_content = "Replace the lowest diffs directory with the diffs directory generated by generate_diffs.py. Remember to delete this file."
    
    response = requests.get(f"{GITHUB_API}/git/commits/{latest_commit_sha}", headers=headers)
    if response.status_code != 200:
      print(f"Error: Unable to fetch commit '{latest_commit_sha}' info: {response.content}")
      sys.exit(1)
    print(f"Commit info fetched successfully.")

    base_tree_sha = response.json()["tree"]["sha"]
    
    blob_data = {
      "content": base64.b64encode(file_content.encode("utf-8")).decode("utf-8"),
      "encoding": "base64"
    }
    
    response = requests.post(f"{GITHUB_API}/git/blobs", headers=headers, json=blob_data)
    if response.status_code != 201:
      print(f"Error: Unable to create blob: {response.content}")
      sys.exit(1)
    print(f"Blob created successfully.")

    blob_sha = response.json()["sha"]
    
    tree_data = {
      "base_tree": base_tree_sha,
      "tree": [
        {
          "path": file_path,
          "mode": "100644",
          "type": "blob",
          "sha": blob_sha
        }
      ]
    }
    
    response = requests.post(f"{GITHUB_API}/git/trees", headers=headers, json=tree_data)
    if response.status_code != 201:
      print(f"Error: Unable to create tree: {response.content}")
      sys.exit(1)
    print(f"Tree created successfully.")

    new_tree_sha = response.json()["sha"]

    commit_message = "Initialize branch for draft Pull Request"
    commit_data = {
      "message": commit_message,
      "tree": new_tree_sha,
      "parents": [latest_commit_sha]
    }
    
    response = requests.post(f"{GITHUB_API}/git/commits", headers=headers, json=commit_data)
    if response.status_code != 201:
      print(f"Error: Unable to create commit: {response.content}")
      sys.exit(1)
    print(f"Commit '{commit_message}' created successfully.")

    new_commit_sha = response.json()["sha"]
    ref_data = {
      "sha": new_commit_sha,
      "force": False
    }

    response = requests.patch(f"{GITHUB_API}/git/refs/heads/{branchName}", headers=headers, json=ref_data)
    if response.status_code == 200:
      print(f"Successfully created 'static/diffs' directory and committed to '{branchName}' branch.")
    else:
      print(f"Error: Unable to update branch reference: {response.content}")
  
  return branchName

if __name__ == '__main__':
  GITHUB_TOKEN = os.environ['GITHUB_TOKEN']
  REPOSITORY = os.environ['GITHUB_REPOSITORY']
  ISSUE_NUMBER = os.environ['ORIGINAL_ISSUE_URL'].split('/')[-1]
  ISSUE_AUTHOR = os.environ['ISSUE_AUTHOR']
  BASE_BRANCH = 'patch_implementations'
  GITHUB_API = f"https://api.github.com/repos/{REPOSITORY}"
  GITHUB_API_REFS = f"{GITHUB_API}/git/refs"
  GITHUB_API_BRANCH = f"{GITHUB_API_REFS}/heads/{BASE_BRANCH}"
  GITHUB_API_ISSUES = f"{GITHUB_API}/issues"
  GITHUB_API_ISSUENUM = f"{GITHUB_API_ISSUES}/{ISSUE_NUMBER}"
  GITHUB_API_PULLS = f"{GITHUB_API}/pulls"
  BASE_GAME_LABELS = {"Pokémon: Yellow Edition": "pokeyellow", "Pokémon: Crystal Edition": 'pokecrystal'}

  headers = {
    "Authorization": f"token {GITHUB_TOKEN}",
    "Accept": "application/vnd.github+json"
  }
  data = parse_issue_form_data()
  if data['implementer'] == 'I will develop it myself':
    new_issue_id = create_issue(data['base_game'], data['description'])
    comment_url = f"{GITHUB_API_ISSUENUM}/comments"
    comment_data = {
      "body": f"This suggestion has been approved. The development process has been moved to issue #{new_issue_id}."
    }
    post_comment(comment_url, comment_data)
    close_issue()
  else:
    new_issue_id = create_draft_pr(data['base_game'], data['description'])
    comment_url = f"{GITHUB_API_ISSUES}/{new_issue_id}/comments"
    comment_data = {
      "body": f"This suggestion has been approved. The issue has been transformed into a draft Pull Request."
    }
    post_comment(comment_url, comment_data)
  