name: Create and link branch to newly created patch development issue

on:
  workflow_dispatch:
    inputs:
      issue_id:
        required: True
        type: number

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    if: ${{ inputs.issue_id }}
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}