name: Create and link branch to newly created patch development issue

on:
  issues:
    types: [ opened ]

jobs:
  create_issue_branch_job:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.labels.*.id }} == 7409398640
    steps:
      - name: Create Issue Branch
        uses: robvanderleek/create-issue-branch@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}