name: Patch Suggestion Approval

on:
  issue_comment:
    types: [created]

jobs:
  approve-patch-suggestion:
    runs-on: ubuntu-latest
    if: >
      startsWith(github.event.comment.body, '/approve') &&
      github.event.comment.user.id == 66346796

    steps:
      - name: Set up Git environment
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        run: pip install requests PyGithub

      - name: Get Original Issue Data
        id: get_issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python python_scripts/get_og_issue_data.py


      - name: Parse Issue Form Data
        id: parse_form
        env:
          ISSUE_DATA: ${{ steps.set_outputs.outputs.issue_data }}
        run: python python_scripts/parse_issue_form_data.py

      - name: Create New Development Issue
        id: create_issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_GAME: ${{ steps.set_outputs.outputs.base_game }}
          IMPLEMENTER: ${{ steps.set_outputs.outputs.implementer }}
          DESCRIPTION: ${{ steps.set_outputs.outputs.description }}
          ISSUE_AUTHOR: ${{ steps.set_outputs.outputs.issue_author }}
        run: python python_scripts/create_new_development_issue.py

      - name: Close Original Issue
        id: close_original_issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ steps.set_outputs.outputs.issue_number }}
        run: python python_scripts/close_original_issue.py
