name: Patch Suggestion Approval

on:
  issue_comment:
    types: [created]

jobs:
  approve-patch-suggestion:
    runs-on: ubuntu-latest
    if: >
      startsWith(github.event.comment.body, '/approve') &&
      github.event.comment.user.id == 66346796

    steps:
      - name: Set up Git environment
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install Dependencies
        run: pip install requests PyGithub

      - name: Create New Development Issue and Close the Original Issue
        id: create_new_issue_close_original_issue
        env:
          ISSUE_BODY: ${{ github.event.issue.body }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_AUTHOR: ${{ github.event.issue.user.login }}
          ORIGINAL_ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: python .github/workflows/python_scripts/create_new_development_issue.py

      - name: Invoke the Workflow that links a branch to the issue
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Create and link branch to newly created patch development issue
          inputs: '{ "issue_id": "${{ env.issue_id }}" }'
