name: Validate patch implementation

on:
  pull_request:
    paths:
      - 'static/diffs/diffs/**'

jobs:
  validate-patch-implementation:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git environment
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Validate patch directory structure
        id: validate_patch_structure
        env:
          CHECKOUT_DIRECTORY: ${{ github.workspace }}
          LABELS: ${{ join(github.event.pull_request.labels.*.name, ',') }}
        run: |
            cd $CHECKOUT_DIRECTORY/static/diffs/
            game_name=$(echo $LABELS | grep -oP '(?<=base_game/)[^,]+')
            python $CHECKOUT_DIRECTORY/.github/workflows/python_scripts/validate_diffs.py -r $game_name
